### ISSUE TITLE
Not enough arches are supported

### ISSUE THREAD

**Issue by xnox** [haskell-primitive/primitive-unaligned#6]
In Ubuntu, I applied the following diff

```
  if arch(i386) || arch(arm)
     hs-source-dirs: src-32
  else
    hs-source-dirs: src-64
```

because not enough architectures were supported by current stanzas. Specifically s390x, riscv64, ppc64le

Note that debian has even more architectures than that! https://buildd.debian.org/status/package.php?p=haskell-primitive-unaligned

Please add more architecture tags, or like default to 64bit, and only list 32bit platforms.

I don't know how the arch tags in cabal work, so sorry that I cannot provide a patch.

You might find https://wiki.debian.org/ArchitectureSpecificsMemo#Summary helpful, as it lists all the architectures Debian supports and what sizes they have.

**Comment by andrewthad** [comment]
Both riscv64 and ppc64le should be handled correctly already because of how `if`-`else` works. Here are the architectures that GHC supports that I am aware of:

* "aarch64"
* "alpha"
* "arm"
* "hppa"
* "hppa1_1"
* "i386"
* "ia64"
* "m68k"
* "mips"
* "mipseb"
* "mipsel"
* "nios2"
* "powerpc"
* "powerpc64"
* "powerpc64le"
* "riscv32"
* "riscv64"
* "rs6000"
* "s390"
* "s390x"
* "sh4"
* "sparc"
* "sparc64"
* "vax"
* "x86_64"

Without searching for each of them, I don't know which ones are 32 bit? Can you list the ones you'd like added?

**Comment by xnox** [comment]
> Both riscv64 and ppc64le should be handled correctly already because of how `if`-`else` works. Here are the architectures that GHC supports that I am aware of:
> 

64-bit
> * "aarch64"
> * "alpha"
> * "ia64"
> * "powerpc64"
> * "powerpc64le"
> * "riscv64"
> * "s390x"
> * "sparc64"
> * "x86_64"

* mips64el

Not mentioned, but there is ghc compiler in debian for mips64el

32-bit
> * "arm"
> * "hppa"
> * "hppa1_1"
> * "i386"
> * "m68k"
> * "mips"
> * "mipseb"
> * "mipsel"
> * "nios2"
> * "powerpc"
> * "riscv32"
> * "rs6000"
> * "s390"
> * "sh4"
> * "sparc"
> * "vax"

I believe is the right split.

> Without searching for each of them, I don't know which ones are 32 bit? Can you list the ones you'd like added?

I would like to have these added for sure:

64-bit:
* mips64el
* s390x
* ia64
* riscv64
* sparc64
* powerpc64le

32-bit
* mipsel
* alpha
* hppa
* m68k
* powerpc

**Comment by andrewthad** [comment]
I realized when I went to add this that I had forgotten that I had written out the conditional source directories as two `if`s rather than an `if`-`else`. I've added everything the lists you provided in https://github.com/haskell-primitive/primitive-unaligned/pull/7. Could you confirm that looks right?
